FROM sonarqube:7.4-community

##############################
# Configure Sonarqube        #
##############################


# https
#ADD ssl/Gogs.crt /etc/cert/Gogs.crt
#ADD ssl/Gogs.key /etc/cert/Gogs.key

# data
#ADD data /data
#COPY conf/sonar.properties /opt/sonarqube/conf/ #For custom properties

#
# eof ..
