FROM sonarqube:lts

##############################
# Configure Sonarqube        #
##############################


# https
#ADD ssl/Sonarqube.crt /etc/cert/Sonarqube.crt
#ADD ssl/Sonarqube.key /etc/cert/Sonarqube.key

# data
#ADD data /data
#COPY conf/sonar.properties /opt/sonarqube/conf/ #For custom properties

#
# eof ..
