version: '2'

networks:
  prodnetwork:
    driver: bridge

volumes:
  ci-training_jenkins:
    driver: local
  ci-training_nexus:
    driver: local
  ci-training_gitbucket:
    driver: local

services:

# https://github.com/sonatype/docker-nexus3
# https://hub.docker.com/r/sonatype/nexus3/
 ci-training_nexus:
  image: sonatype/nexus3
  ports:
    - "30081:8081"
  environment:
    - JAVA_MIN_MEM=256m
    - JAVA_MAX_MEM=1200m
  volumes:
    - ci-training_nexus:/nexus-data
  networks:
    - prodnetwork

 ci-training_jenkins:
  build: ./jenkins
  ports:
    - "30080:8080"
  networks:
    - prodnetwork
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ci-training_jenkins:/var/lib/jenkins/
  depends_on:
    - ci-training_nexus
    - ci-training_gitbucket
#    - sonar
  environment:
    - NEXUS_PORT=8081


# https://github.com/f99aq8ove/docker-gitbucket
# https://hub.docker.com/r/f99aq8ove/gitbucket/
 ci-training_gitbucket:
  image: f99aq8ove/gitbucket:latest
  restart: always
  networks:
    - prodnetwork
  ports:
    - "30082:8080"
    - "30022:30022"
  volumes:
    - ci-training_gitbucket:/gitbucket
