version: '2'

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1

volumes:
  ci-jenkins:
  ci-nexus:
  ci-gogs:

services:
# https://hub.docker.com/r/jenkins/jenkins/
# https://github.com/jenkinsci/docker
 ci-jenkins:
  build: ./jenkins
  image: ci-jenkins:latest
  hostname: jenkins
  depends_on:
    - ci-nexus
    - ci-gogs
  environment:
    - NEXUS_PORT=8081
  networks:
    internal:
      ipv4_address: 10.0.0.20
      aliases:
      - jenkins
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ci-jenkins:/var/jenkins_home/

# https://github.com/sonatype/docker-nexus3
# https://hub.docker.com/r/sonatype/nexus3/
 ci-nexus:
  build: ./nexus
  image: ci-nexus:latest
  hostname: nexus
  environment:
    - JAVA_MIN_MEM=256m
    - JAVA_MAX_MEM=1200m
  volumes:
    - ci-nexus:/nexus-data
  networks:
    internal:
      ipv4_address: 10.0.0.21
      aliases:
      - nexus

# https://github.com/gogits/gogs/tree/master/docker
# https://hub.docker.com/r/gogs/gogs/
 ci-gogs:
  build: ./gogs
  image: ci-gogs:latest
  hostname: gogs
  volumes:
    - ci-gogs:/data
  networks:
    internal:
      ipv4_address: 10.0.0.30
      aliases:
      - gogs
      - git
      
# https://hub.docker.com/_/nginx/
# https://github.com/nginxinc/docker-nginx/blob/f603bb3632ea6df0bc9da2179c18eb322c286298/mainline/stretch/Dockerfile
 ci-nginx:
  build: ./nginx
  image: ci-nginx:latest
  hostname: nginx
  depends_on:
    - ci-nexus
    - ci-gogs
    - ci-jenkins
  ports:
    - "443:443"
  networks:
    internal:
      ipv4_address: 10.0.0.10
      aliases:
      - nginx
