version: '2'

networks:
  internal:

volumes:
  ci-jenkins:
  ci-maven-local-repo:
  ci-nexus:
  ci-gogs:


services:
 ci-jenkins:
  build: ./jenkins
  image: ci-jenkins:latest
  ports:
    - "30080:8080"
   #- "50000:50000" JNLP not needed
  depends_on:
    - ci-nexus
    - ci-gogs
  environment:
    - NEXUS_PORT=8081
  networks:
    - internal
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ci-jenkins:/var/lib/jenkins/
    - ci-maven-local-repo:/home/jenkins/.m2 # TODO Geht?

# https://github.com/sonatype/docker-nexus3
# https://hub.docker.com/r/sonatype/nexus3/
 ci-nexus:
  build: ./nexus
  image: ci-nexus:latest
  ports:
    - "30081:8081"
  environment:
    - JAVA_MIN_MEM=256m
    - JAVA_MAX_MEM=1200m
  volumes:
    - ci-nexus:/nexus-data
  networks:
    - internal



# https://github.com/gogits/gogs/tree/master/docker
# https://hub.docker.com/r/gogs/gogs/
 ci-gogs:
  build: ./gogs
  image: ci-gogs:latest
  ports:
    - "30082:3000" # TODO Move to 8082
  volumes:
    - ci-gogs:/data
  networks:
    - internal
