version: '2'

networks:
  internal:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1

volumes:
  ci-jenkins:
  ci-nexus:
  ci-gogs:


services:
 ci-jenkins:
  build: ./jenkins
  image: ci-jenkins:latest
  hostname: jenkins
  ports:
    - "30080:30080"
   #- "50000:50000" JNLP not needed
  depends_on:
    - ci-nexus
    - ci-gogs
  environment:
    - NEXUS_PORT=8081
  networks:
    internal:
      ipv4_address: 172.16.238.10
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ci-jenkins:/var/jenkins_home/

# https://github.com/sonatype/docker-nexus3
# https://hub.docker.com/r/sonatype/nexus3/
 ci-nexus:
  build: ./nexus
  image: ci-nexus:latest
  hostname: nexus
  ports:
    - "30081:8081" # TODO Port ändern
  environment:
    - JAVA_MIN_MEM=256m
    - JAVA_MAX_MEM=1200m
  volumes:
    - ci-nexus:/nexus-data # TODO Stimmt das?
  networks:
    internal:
      ipv4_address: 172.16.238.11



# https://github.com/gogits/gogs/tree/master/docker
# https://hub.docker.com/r/gogs/gogs/
 ci-gogs:
  build: ./gogs
  image: ci-gogs:latest
  hostname: gogs
  ports:
    - "30082:30082"
  volumes:
    - ci-gogs:/data
  networks:
    internal:
      ipv4_address: 172.16.238.12
