version: '2'

networks:
  prodnetwork:
    driver: bridge

volumes:
  ci-tool-stack_jenkins:
    driver: local
  ci-tool-stack_nexus:
    driver: local
  ci-tool-stack_gitbucket:
    driver: local

services:

# https://github.com/sonatype/docker-nexus3
# https://hub.docker.com/r/sonatype/nexus3/
 nexus:
  image: sonatype/nexus3
  ports:
    - "18081:8081"
  environment:
    - JAVA_MIN_MEM=256m
    - JAVA_MAX_MEM=1200m
  volumes:
    - ci-tool-stack_nexus:/nexus-data
  networks:
    - prodnetwork

 jenkins:
  build: ./jenkins
  ports:
    - "18080:8080"
  networks:
    - prodnetwork
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ci-tool-stack_jenkins:/var/lib/jenkins/
  depends_on:
    - nexus
    - gitbucket
#    - sonar
  environment:
    - NEXUS_PORT=8081


# https://github.com/f99aq8ove/docker-gitbucket
# https://hub.docker.com/r/f99aq8ove/gitbucket/
 gitbucket:
  image: f99aq8ove/gitbucket:latest
  restart: always
  networks:
    - prodnetwork
  ports:
    - "17080:8080"
    - "17222:17222"
  volumes:
    - ci-tool-stack_gitbucket:/gitbucket
